# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectName: 'EventHub'
  testProjectName: 'EventHub.Tests'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build $(projectName) $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '$(projectName)'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Test $(testProjectName)'
  inputs:
    command: 'test'
    projects: '$(testProjectName)'
- task: DotNetCoreCLI@2
  displayName: 'Pack $(projectName)'
  inputs:
    command: 'pack'
    packagesToPack: '**/EventHub.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
- task: DotNetCoreCLI@2
  displayName: 'Push to Local Feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '756019a8-6230-4307-a470-c82ea4fd61dd'
- task: PublishBuildArtifacts@1
  displayName: 'Publish BuildArtifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'